language: python

python: 
  - "3.6" 

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - export 
  - export FLASK_APP="$TRAVIS_BUILD_DIR/src/runserver.py"
  - export FLASK_DEBUG=1
  - export JSON_FILE=src/app/config.json

